### ISSUE TITLE
Clarifications for the JOSS paper

### ISSUE THREAD

**Issue by dpsanders** [sp94/Peacock.jl#13]
- In the first paragraph you state that the package is for "studying photonic crystals" but not what you study about them.

- In the statement of need you then refer to eigensolutions of a crystal, but it's not clear which object you are calculating eigenproperties of.

- You mix "eigensolutions" and "eigenmodes".

- At the end of the paragraph you talk about photonic bands. Thus it just seems like some rearranging is required.  But perhaps more mathematical detail about the system should be included?

- In the first reference, "hgte" should presumably be "HgTe"

- Physical review letters -> Physical Review Letters (capitalisation)

- Please check the details of the remaining references. Journals should have initial letters of each word capitalised.

Thanks!

**Comment by dpsanders** [comment]
- The Rumpf paper has no information other than a title.

**Comment by dpsanders** [comment]
- The Joannopoulos book has the wrong title.

**Comment by dpsanders** [comment]
- "Innoació n" -- remove space

**Comment by sp94** [comment]
Hi @dpsanders, thanks for taking the time to go through this

### Main text

> In the first paragraph you state that the package is for "studying photonic crystals" but not what you study about them.

Now reads "for solving Maxwell's equations using the Plane Wave Expansion Method in order to predict the optical properties of photonic crystals"

> In the statement of need you then refer to eigensolutions of a crystal, but it's not clear which object you are calculating eigenproperties of.

Instead of "eigensolutions of a crystal" I now say "eigensolutions of Maxwell's equations for photonic crystals" to make this clearer

> You mix "eigensolutions" and "eigenmodes".

I have changed the paper to say "eigensolutions" when I mean both eigenvalue+eigenmode

> At the end of the paragraph you talk about photonic bands. Thus it just seems like some rearranging is required. But perhaps more mathematical detail about the system should be included?

I think "bands" may be extra jargon, so I have removed it. eg It now says "topological photonic crystals" instead of "band topology in photonic crystals". I also split the statement of need into two paragraphs to make it clearer where the comparison to existing software begins. Does it still seem like rearranging is required?

### References

- [x] hgte -> HgTE
- [x] Physical review letters -> Physical Review Letters (capitalisation)
- [x] Please check the details of the remaining references. Journals should have initial letters of each word capitalised.
- [x] The Rumpf paper has no information other than a title.
  * The Rumpf reference is a PhD thesis so I have changed its bibtype to pdfthesis and added the university
- [x] The Joannopoulos book has the wrong title.
  * added full title and edition
- [x] "Innovació n" -- remove space

**Comment by dpsanders** [comment]
Thanks.

Another question: Have you asked for permission to include the figure from the PNAS paper? If not I think it should be removed.

**Comment by sp94** [comment]
Hi, we asked for permission already. Do I need to provide this to JOSS?

**Comment by dpsanders** [comment]
OK that's great, thanks!

**Comment by sp94** [comment]
Hi @dpsanders, is there anything else to do before closing this issue?
